### ISSUE TITLE
error when compiling with your VIdeoView class

### ISSUE THREAD

**Issue by moster67** [LISNR/libvlc#1] opened 2016-02-11 15:13 UTC
Hi, 
I am trying your videoview class but I get problems when I try to compile the project using configure.sh for VLC
I commented out your methods about "fd" so that should not be the problem.

I replaced the original (nearly empty) videoview class with your videoview class in the "vlc-android/libvlc/src/org/videolan/libvlc/media/" directory. Then I started to compile the vlc-project but I get compiling problems as shown in the below log:

`/home/osboxes/vlc-android/libvlc/src/org/videolan/libvlc/media/VideoView.java:81: error: constructor MediaPlayer in class MediaPlayer cannot be applied to given types;
        mediaPlayer = new MediaPlayer(sLibVLC);
                      ^
  required: no arguments
  found: LibVLC
  reason: actual and formal argument lists differ in length
/home/osboxes/vlc-android/libvlc/src/org/videolan/libvlc/media/VideoView.java:91: error: package IVLCVout does not exist
        mediaPlayer.getVLCVout().addCallback(new IVLCVout.Callback() {
                                                         ^
/home/osboxes/vlc-android/libvlc/src/org/videolan/libvlc/media/VideoView.java:126: error: cannot find symbol
        mediaPlayer.setEventListener(new MediaPlayer.EventListener() {
                                                    ^
  symbol:   class EventListener
  location: class MediaPlayer
/home/osboxes/vlc-android/libvlc/src/org/videolan/libvlc/media/VideoView.java:166: error: cannot find symbol
        final Media media = new Media(sLibVLC, path);
              ^
  symbol:   class Media
  location: class VideoView
/home/osboxes/vlc-android/libvlc/src/org/videolan/libvlc/media/VideoView.java:166: error: cannot find symbol
        final Media media = new Media(sLibVLC, path);
                                ^
  symbol:   class Media
  location: class VideoView
/home/osboxes/vlc-android/libvlc/src/org/videolan/libvlc/media/VideoView.java:172: error: cannot find symbol
        final Media media = new Media(sLibVLC, uri);
              ^
  symbol:   class Media
  location: class VideoView
/home/osboxes/vlc-android/libvlc/src/org/videolan/libvlc/media/VideoView.java:172: error: cannot find symbol
        final Media media = new Media(sLibVLC, uri);
                                ^
  symbol:   class Media
  location: class VideoView
Note: /home/osboxes/vlc-android/libvlc/src/org/videolan/libvlc/util/VLCUtil.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/osboxes/vlc-android/libvlc/src/org/videolan/libvlc/VLCObject.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
7 errors
:libvlc:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.`

There are 2 MediaPlayer.java files in the vlclib sources:
-one in "vlc-android/libvlc/src/org/videolan/libvlc/
-other one in "vlc-android/libvlc/src/org/videolan/libvlc/media/"
Could this be the problem?

Any help/suggestion would be appreciated. Thank you.

**Comment by eyecreate** [comment] 2016-02-11 17:42
This code was built in order to get a basic videoplayer view working and also play assets from the installed apk directly. If you don't need the last part, you can ignore adding the file.c changes, but the ones involving fd in VideoView shouldn't interfere if you don't call it.
Yes, it looks like the issue is the wrong MediaPlayer is being looked at when compiling. The one intended(and should be listed in the imports) is not in the media package. It should already reference it by full package name in the code in the repo(to prevent mixing up with similar named classes), so unless you made other changes, it should work. Double check that is the case in what you have.

**Comment by moster67** [comment] 2016-02-13 09:38
I did everything from scratch again and now it compiled fine. I guess I must have changed something.
Many thanks for your help.

PS: why don't push it to the official git? It seems they started with the VideoView class but then stopped working on it.

**Comment by eyecreate** [comment] 2016-02-13 14:09
Glad you got it working now. 
I have tried submitting patches to vlc, but there is disagreement about the way some things are being done. I can understand as these patches were mostly made to get some results and not necessarily for best code.  I have been assured that the VideoView class is going to be finished internally, just not sure when. For that reason, I haven't been too worried about making this patch into one that would be accepted by vlc.
I'll close this issue since it seems you've got it compiled now.

**Closed by eyecreate** 2016-02-13 14:09 UTC
